### ISSUE TITLE
Missing LICENSE and COPYRIGHT files

### ISSUE THREAD

**Issue by ralphlange** [epics-base/exampleCPP#1]
*From Andrew Johnson &lt;anj_AT_aps.anl.gov&gt;:*

Module is missing LICENSE and COPYRIGHT files which are referred to in source code header comments within the module

**Comment by anjohnson** [comment]
I have added the LICENSE file in my branch of exampleCPP, but I'm not sure who should be listed in the COPYRIGHT file. I'm seeing commits in the git log from James Rowland, David, Matej and Ralph, although it looks like James and David (i.e. Diamond) added almost all of the C++ source code. David, I don't see any Diamond copyrights given in the other module COPYRIGHT files, can you advise what to use please.

**Comment by dhickin** [comment]
<p>Resolved by merge of epics-base/exampleCPP/pull/2.</p>
