### ISSUE TITLE
Possible issues with Windows builds

### ISSUE THREAD

**Issue by ralphlange** [epics-base/exampleCPP#24]
From W. Todd Sneed ( todd.sneed _AT_ nhancetech.com ):

(He refers to the 4.5.0.2 version of the examples:)
[...]
Finally, there were errors in the cout<< statements in examplePvaClientProcess and example PVAClientPUt, so I simply commented out the offending lines, because they were example programs.

**Comment by mrkraimer** [comment]
On 08/16/2016 11:13 AM, Ralph Lange wrote:
>
> From W. Todd Sneed ( todd.sneed /AT/ nhancetech.com ):
>
> (He refers to the 4.5.0.2 version of the examples:)
> [...]
> Finally, there were errors in the cout<< statements in 
> examplePvaClientProcess and example PVAClientPUt, so I simply 
> commented out the offending lines, because they were example programs.
>


???

In  EPICS Version 4.5, examplePvaClientProcess and 
examplePvaClientProcess were in pvExampleTestCPP.
Is this what Todd was talking about?

Note that for EPICS Version 4.6 all code that was in pvaClientTestCPP 
and pvExampleTestCPP are now in exampleCPP.

Marty

**Comment by ralphlange** [comment]
This is why I added the issue here, and not in the old place.

Todd had the very same issues compiling 4.6.0-pre1, at the new location of the code.

**Comment by mrkraimer** [comment]
On what platform did Todd see the problem?
What were the error messages?

I looked at the code and do not see anything wrong.

Note also that the following show success
https://openepics.ci.cloudbees.com/view/EPICS%20V4%20C++/
https://jenkins.aps.anl.gov/view/EPICS%20V4/

**Comment by ralphlange** [comment]
The platform was Windows (see issue title).

CloudBees Jenkins does not build for Windows.
APS Jenkins does build on exactly one combination of Windows and compiler. (I think Win7 with some version of the MS compiler.)

Todd wrote:
We have tried XP, Windows 7, and Windows 10 with different compilers ranging from gnuCPP to Microsoft from Visual Studio 2008, 2012, and 2015.  For the most part, some versions build without modification with certain compilers.  The latest versions compile on windows.  So for my development effort, I decided to use 3.15.4 as the base version of EPICS built with visual studio 2015 32 bit, running on windows 10 64bit.

**Comment by mrkraimer** [comment]
I have no idea what to do.

The only widows builds I can look at for errors is on
 https://jenkins.aps.anl.gov/view/EPICS%20V4/

I do look at these and see that the various windows builds do work.
And currently all show success.

**Comment by anjohnson** [comment]
I'm adding V4 build jobs for Windows that compile against the Base-3.15 branch in case that's any help with this. Unfortunately our Windows build slave is rather heavily used (the MS compiler is a bit slow, and I only run one 64-bit build job at once to avoid upstream/downstream problems).

**Comment by anjohnson** [comment]
My new V4 3.15-*-win64 and -win64s jobs all finished building without any errors, so the Base version isn't what's causing Todd's problem. I'm using Visual Studio 2010 64-bit. I haven't created any 32-bit WIndows V4 jobs on Jenkins, but I just tried a win32-x86 build of the EPICS-CPP-4.6.0-pre1 bundle against Base-3.15 on my Windows workstation and it had no build failures either.

I think there's something strange about Todd's setup, the problem about the linker that Ralph reported in an issue against the bundleCPP module suggests that maybe he has too much other stuff in his path. He needs to _properly_ solve the problem with building Base first, then look at building V4.

**Comment by anjohnson** [comment]
Mark Rivers reported what appears to be the same problem, here are his error messages:
```
make[3]: Entering directory 'H:/epics-devel/epicsV4/bundleCPP/exampleCPP/exampleClient/src/O.windows-x64-static-vs2015'
cl /nologo /EHsc /GR -c              /favor:blend   /nologo /D__STDC__=0 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_NONSTDC_NO_DEPRECATE   /Ox /GL   /W3 /w44355        /MT -DEPICS_DLL_NO /TP   -I. -I..\\O.Common -I. -I.. -I..\\..\\include\\os\\WIN32 -I..\\..\\include -IH:\epics-devel\base-3.14.12.5\\include\\os\\WIN32 -IH:\epics-devel\base-3.14.12.5\\include    -IH:\\epics-devel\\epicsV4\\bundleCPP\\pvDatabaseCPP\\include  -IH:\\epics-devel\\epicsV4\\bundleCPP\\pvaSrv\\include  -IH:\\epics-devel\\epicsV4\\bundleCPP\\pvaClientCPP\\include  -IH:\\epics-devel\\epicsV4\\bundleCPP\\pvAccessCPP\\include  -IH:\\epics-devel\\epicsV4\\bundleCPP\\normativeTypesCPP\\include  -IH:\\epics-devel\\epicsV4\\bundleCPP\\pvDataCPP\\include  -IH:\\epics-devel\\epicsV4\\bundleCPP\\pvCommonCPP\\include        ..\\examplePvaClientProcess.cpp
examplePvaClientProcess.cpp
H:\epics-devel\epicsV4\bundleCPP\pvDataCPP\include\pv/pvData.h(456): warning C4800: 'epics::pvData::boolean': forcing value to bool 'true' or 'false' (performance warning)
..\examplePvaClientProcess.cpp(28): error C2678: binary '<<': no operator found which takes a left-hand operand of type 'std::ostream' (or there is no acceptable conversion)
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\ostream(497): note: could be 'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(std::basic_streambuf<char,std::char_traits<char>> *)'
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\ostream(477): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(const void *)'
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\ostream(457): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(long double)'
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\ostream(437): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(double)'
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\ostream(417): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(float)'
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\ostream(396): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(unsigned __int64)'
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\ostream(376): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(__int64)'
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\ostream(355): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(unsigned long)'
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\ostream(335): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(long)'
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\ostream(315): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(unsigned int)'
...
```
My analysis will follow in another comment.

**Comment by anjohnson** [comment]
The error C2678 on line 28 of examplePvaClientProcess.cpp is for this code:
```c++
cout <<  channel->get("field()")->getData()->showChanged(cout) << endl;
```
The channel variable is a PvaClientChannelPtr which is a typedef for std::tr1::shared_ptr<PvaClientChannel>. The PvaClientChannel class defines the method
```c++
PvaClientGetPtr get(std::string const & request = "field(value,alarm,timeStamp)");
```
The PvaClientGetPtr is a typedef for std::tr1::shared_ptr<PvaClientGet> and the PvaClientGet class defines the method
```c++
PvaClientGetDataPtr getData();
```
which interestingly is marked as deprecated (Marty — example programs really shouldn't be using deprecated APIs, I hope you're thinking about a fix for this). As before, PvaClientGetDataPtr is a typedef for std::tr1::shared_ptr<PvaClientGetData> and the PvaClientGetData class defines the method 
```c++
std::ostream & showChanged(std::ostream & out);
```
However at this point my C++-foo escapes me and I think I understand the compiler's problem; it's trying to find some routine with a signature like this:
```c++
std::ostream & operator << (std::ostream &, std::ostream &);
```
I.e. a binary (2-arg) function that takes the arg's cout on the LHS and the value returned by the showChanged() method on the RHS, that returns cout. There is no such function defined in the C++ standard http://www.cplusplus.com/reference/ostream/ostream/operator%3C%3C/ but I'm going to guess that either the GNU implementation provides one or it is somehow reading the above code differently than I am.

I think the code in examplePvaClientProcess.cpp on both lines 28 and 30 should be this:
```c++
channel->get("field()")->getData()->showChanged(cout) << endl;
```
i.e. remove the leading `cout <<` part. The same fix is probably required at 8 places in examplePvaClientPut.cpp.

**Comment by anjohnson** [comment]
Patch file showing the fixes needed.
[exampleCPP.patch](https://github.com/epics-base/exampleCPP/files/652704/exampleCPP.patch.txt)

**Comment by mrkraimer** [comment]
I made the changes shown in the patch file provided by Andrew (Thanks Andrew!!);
I don't want to close this issue since I have no way to test on windows.

**Comment by anjohnson** [comment]
These build errors should now be fixed.

**Comment by MarkRivers** [comment]
I just tested the patch on Visual Studio 2015 Community edition, static build, base 3.14.12.5.  It works. Thanks!
