### ISSUE TITLE
exampleCPP/pvDatabaseRPC: epicsShare problems

### ISSUE THREAD

**Issue by mrkraimer** [epics-base/exampleCPP#27]
While building with base-3.15.5 on linux I see many warnings like
../pv/point.h:35:23: warning: attribute ignored in declaration of ‘class epics::exampleCPP::exampleRPC::Point’ [-Wattributes]
 epicsShareClass class Point

I will try to fix these warnings but will need someone else to check that windows builds work
.

**Comment by mrkraimer** [comment]
If point.h and device.h are changed so that all use of epicsShare is removed then the warnings disappear.

I think this is a good fix for the following reasons:

1) On linux lib/linux-x86_64/libexampleRPC.so is identical either way.
2) Both point and device are part of the example and not meant to be used outside the example.

Any comments before I push the changes?

**Comment by ralphlange** [comment]
The epicsShare... macros are necessary for Windows and expand to NOPs on Linux, so comparing the Linux libraries is of limited use.
The important check is compiling and running the examples on Windows. (And Linux, of course.)

**Comment by mdavidsaver** [comment]
On 12/15/2016 10:25 AM, Ralph Lange wrote:
> ... expand to NOPs on Linux,

Not necessarily with Base >=3.15.  GCC w/ -fvisibility=hidden while not
exactly equivalent, will error in many of the same places.  I've used
this before to troubleshoot dllimport/export issues.  Recently (circa
debian 8) I've preferred to use cross mingw, which is stricter.

https://github.com/epics-base/epics-base/blob/3.16/src/libCom/misc/shareLib.h#L139

**Comment by ralphlange** [comment]
And cross mingw is a Linux-hosted compiler that Marty could use to test
compilation, correct?
(Running the Windows binaries still needs a Windows machine, obviously.)

**Comment by mdavidsaver** [comment]
On 12/15/2016 10:54 AM, Ralph Lange wrote:
> And cross mingw is a Linux-hosted compiler that Marty could use to test
> compilation, correct?

apt-get install mingw-x64

https://github.com/mdavidsaver/epics-base/blob/integration/build-travis.sh#L46

> (Running the Windows binaries still needs a Windows machine, obviously.)

WINE works for running unit tests.  Not that this is needed to verify
correct linking.

**Comment by anjohnson** [comment]
Marty used to run Fedora, but I don't know what he uses now. There is an equivalent MinGW cross-build package for RHEL/Fedora though.

**Comment by anjohnson** [comment]
`epicsShareClass class Point` should be spelled `class epicsShareClass Point`

**Comment by mrkraimer** [comment]
I have pushed changes that should fix this problem.
I did use epicsShareClass.

**Comment by mrkraimer** [comment]
I see that the 
https://jenkins.aps.anl.gov/view/EPICS%20V4/job/3.15-example-win64/
and
https://jenkins.aps.anl.gov/view/EPICS%20V4/job/epics-example-win64/

now fail but the windows  shared builds do succeed;
The problem appears to be in
exampleCPP/pvDatabaseRPC/src/pv/point.h
In particular the code:

class epicsShareClass IllegalOperationException : public std::runtime_error
{
public:
    IllegalOperationException(const std::string & message)
    : runtime_error(message)
    {
    }
};

I do not know how to fix this.
Does anyone know how to fix it?

**Comment by mrkraimer** [comment]
I think I found a fix for windows non-shared builds

**Comment by mrkraimer** [comment]
No I am really stuck.
It is complaining about 
class 'std::runtime_error' used as base for dll-interface class 'epics::pvAccess::RPCRequestException'

Anyone have an idea how to fix this?

**Comment by mrkraimer** [comment]
Previously I said fix non-shared for window.
I should have said shared.

I have push more changes to fix problem.

**Comment by anjohnson** [comment]
In case you were getting confused I should let you know that the 3.15-example.win64 Jenkins job was being compiled using `make -O -j4` which means that the build was **not** stopping at the first error, and to find the actual error message you would have had to search up through the complete build output log. I have removed the parallel build flags from that job for now, but using parallel builds was reducing the job build time from over 9 minutes down to under 2.5 minutes on Windows. Most of the other module jobs are now using parallel make where I can enable it (3.14-based Windows DLL builds cannot be built in parallel). I will re-enable parallel builds once we have this issue fixed.

Looking at the current error, I now think that in the specific case of `class Point` the right solution is actually what you suggested earlier, removing the `epicsShareClass` macro. This class consists only of POD and non-virtual inline functions that are all declared in the pv/point.h file, so it has nothing that needs to be compiled into or imported from a DLL. This would not have been the right solution for `class Device` which has virtual functions and a separate `device.cpp` source file, but I think it is correct for Point. Please try that.

**Comment by mrkraimer** [comment]
OK I will change Point,
I also thought of what could be the problem with Device.
Helps to just take Daisy for a walk and let mind wander
I am just starting changes.

**Comment by mrkraimer** [comment]
I see that after the changes to Point, all the windows builds are successful.
It is a mystery to me why this fixed the windows shared builds.

Andrew,

If all looks OK to You can You close this issue?
What about issue 24.
Can that also be closed?

**Comment by anjohnson** [comment]
These were the error messages from the failing link command:
```
link /nologo /subsystem:windows /dll -LTCG -incremental:no -opt:ref -release  /MACHINE:X64      /implib:exampleRPC.lib /out:exampleRPC.dll          exampleRPC.obj exampleRPCRegister.obj device.obj     C:\jenkins\win64-1\workspace\epics-pvDatabase-win64\\lib\\windows-x64\\pvDatabase.lib  C:\jenkins\win64-1\workspace\epics-pvAccess-win64\\lib\\windows-x64\\pvAccess.lib  C:\jenkins\win64-1\workspace\epics-pvData-win64\\lib\\windows-x64\\pvData.lib  C:\jenkins\win64-1\workspace\epics-base-3.14-win64\\lib\\windows-x64\\Com.lib  
   Creating library exampleRPC.lib and object exampleRPC.exp
exampleRPC.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl epics::exampleCPP::exampleRPC::Point::Point(class epics::exampleCPP::exampleRPC::Point const &)" (__imp_??0Point@exampleRPC@exampleCPP@epics@@QEAA@AEBV0123@@Z)
exampleRPC.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl epics::exampleCPP::exampleRPC::Point::Point(double,double)" (__imp_??0Point@exampleRPC@exampleCPP@epics@@QEAA@NN@Z)
device.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: class epics::exampleCPP::exampleRPC::Point __cdecl epics::exampleCPP::exampleRPC::Point::operator=(class epics::exampleCPP::exampleRPC::Point const &)" (__imp_??4Point@exampleRPC@exampleCPP@epics@@QEAA?AV0123@AEBV0123@@Z)
device.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl epics::exampleCPP::exampleRPC::Point::Point(void)" (__imp_??0Point@exampleRPC@exampleCPP@epics@@QEAA@XZ)
exampleRPC.dll : fatal error LNK1120: 4 unresolved externals
C:\jenkins\win64-1\workspace\epics-base-3.14-win64/configure/RULES_BUILD:303: recipe for target 'exampleRPC.dll' failed
```

The important parts are these:
```
error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl epics::exampleCPP::exampleRPC::Point::Point(class epics::exampleCPP::exampleRPC::Point const &)"
error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl epics::exampleCPP::exampleRPC::Point::Point(double,double)"
error LNK2001: unresolved external symbol "__declspec(dllimport) public: class epics::exampleCPP::exampleRPC::Point __cdecl epics::exampleCPP::exampleRPC::Point::operator=(class epics::exampleCPP::exampleRPC::Point const &)"
error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl epics::exampleCPP::exampleRPC::Point::Point(void)
```

These are all inline methods defined inside the pv/point.h header. For some obscure reason the linker was looking for binary versions of these inside some shared library, presumably because the class was marked with epicsShareClass, even though the compiler had already been given full inline definitions so the linker shouldn't need them at all. That's rather dumb on the part of the linker, but it is from Microsoft after all.

I turned on parallel builds again BTW.

Thanks,

- Andrew
