### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by forestmojo** [epics-base/exampleCPP#70]
hi, Marty:

I have some problem when compiling exampleCPP, would you please check what's it? thanks a lot for your help.
/usr/bin/g++  -D_GNU_SOURCE -D_DEFAULT_SOURCE            -D_X86_64_  -DUNIX  -Dlinux      -O3 -g   -Wall      -mtune=generic      -m64 -fPIC -I. -I../O.Common -I. -I. -I.. -I../../include/compiler/gcc -I../../include/os/Linux -I../../include -I/home/geyang/epics/r7.0.5/base/include/compiler/gcc -I/home/geyang/epics/r7.0.5/base/include/os/Linux -I/home/geyang/epics/r7.0.5/base/include -I/home/geyang/epics/r7.0.5/base/include/compiler/gcc -I/home/geyang/epics/r7.0.5/base/include/os/Linux -I/home/geyang/epics/r7.0.5/base/include                          -c ../scalarLimitRecord.cpp
../scalarLimitRecord.cpp: In constructor â€˜epics::scalarLimit::ScalarLimitRecord::ScalarLimitRecord(const string&, const PVStructurePtr&, int, const string&)â€™:
../scalarLimitRecord.cpp:52:50: error: no matching function for call to â€˜epics::pvDatabase::PVRecord::PVRecord(const string&, const PVStructurePtr&, int&, const string&)â€™
   52 | : PVRecord(recordName,pvStructure,asLevel,asGroup)
      |                                                  ^
In file included from ../scalarLimitRecord.cpp:18:
/home/geyang/epics/r7.0.5/base/include/pv/pvDatabase.h:241:5: note: candidate: â€˜epics::pvDatabase::PVRecord::PVRecord(const string&, const PVStructurePtr&)â€™
  241 |     PVRecord(
      |     ^~~~~~~~
/home/geyang/epics/r7.0.5/base/include/pv/pvDatabase.h:241:5: note:   candidate expects 2 arguments, 4 provided
make[3]: *** [/home/geyang/epics/r7.0.5/base/configure/RULES_BUILD:263: scalarLimitRecord.o] Error 1
make[3]: Leaving directory '/home/geyang/tmp/exampleCPP/scalarLimit/src/O.linux-x86_64'
make[2]: *** [/home/geyang/epics/r7.0.5/base/configure/RULES_ARCHS:58: install.linux-x86_64] Error 2
make[2]: Leaving directory '/home/geyang/tmp/exampleCPP/scalarLimit/src'
make[1]: *** [/home/geyang/epics/r7.0.5/base/configure/RULES_DIRS:85: src.install] Error 2
make[1]: Leaving directory '/home/geyang/tmp/exampleCPP/scalarLimit'
make: *** [/home/geyang/epics/r7.0.5/base/configure/RULES_DIRS:85: scalarLimit.install] Error 2

**Comment by mrkraimer** [comment]
Sorry I missed this message until I was just cleaning up my email.
Have you read
https://mrkraimer.github.io/website/developerGuide/pvService/pvService.html
Look at section 2 Building exampleCPP from an EPICS7 release

**Comment by forestmojo** [comment]
hi, Marty:

as your mentioned, it can be compiled, thanks a lot.
  





Best wishes
Geyang 2021-06-22



##############on 2021-06-21, ***@***.*** wrote:###############
Sorry I missed this message until I was just cleaning up my email.
Have you read
https://mrkraimer.github.io/website/developerGuide/pvService/pvService.html
Look at section 2 Building exampleCPP from an EPICS7 release
―
